### PR TITLE
feat (i18n): translate to Portuguese

### PR DESCRIPTION
**Pull request by mribeirodantas**
Creates a file with translations into Portuguese.

### CODE REVIEW

**Comment by pvictor** [comment]
Thanks @mribeirodantas !
If you will, you can also add translation in the same way in package [datamods](https://github.com/dreamRs/datamods), which contain the import data module used in esquisse.
There's a brazilian portuguese file there, I don't know if it's ok for you.

Victor

**Comment by mribeirodantas** [comment]
Thanks, @pvictor. I just checked the Portuguese translation in the package you mentioned. Seems fine!

**Comment by mribeirodantas** [comment]
One question, @pvictor. Don't you think we should also translate to other languages the fields in esquisse (fill, color, size, group, facet, variables) and the quotation at the top (check below)?

_"Les grandes personnes ne comprennent jamais rien toutes seules, et c'est fatigant, pour les enfants, de toujours et toujours leur donner des explications."_

**Comment by beatrizmilz** [comment]
I just want to thank you for this PR! Really useful 🎉 I just added `datamods::set_i18n("pt")` into my app's server, and esquisse was translated to Portuguese.

**Pull request merged**
