### PR TITLE
add turkish translation

### PR DESCRIPTION
**Pull request by sbalci**
added turkish translation as a csv file

### CODE REVIEW

**Comment by pvictor** [comment]
Çok teşekkürler ! (from Google translate :wink:)

**Comment by pvictor** [comment]
The same mechanism exist in package [datamods](https://github.com/dreamRs/datamods) where the import module is located, if you have time.

**Comment by sbalci** [comment]
I use github copilot in vscode and seems to work near perfect in translating. I will take a look into datamods as well.

**Comment by pvictor** [comment]
I appreciate your effort 🙂

**Pull request merged**
