### PR TITLE
added functionalities, facet, facet grid, xy limits, etc.

### PR DESCRIPTION
**Pull request by xiangnandang**
Hi Victor @pvictor ,

Thank you for the very nicely developed package, and I've been using it for a couple of projects. I had submitted a similar pull request previously, but the pull request did not pass the build check, largely because I'm very new with R package development in general.

Here, I have cleaned up my code, making sure there was no warning/errors during build check on my local copy.

I'm adding the following functionalities:
1. ncol and nrow arguments for facet_wrap, to allow customization of how many rows or columns in facet wrap displays
2. facet_row and facet_col features to allow facet_grid call from ggplot2
3. x and y limits of the plots

Please let me know if you need more information from me. I'm looking forward to incorporating these features to benefit more users, as well looking forward to developing more features/enhancements for this excellent package.

Best,
Xiangnan (dang_xiangnan@lilly.com)

### CODE REVIEW

**Comment by pvictor** [comment]
Hello @xiangnandang ,

Sorry I didn't answer earlier (a lot of things to do and little time to do them), this is good work and neat additions to the package ! I'll take time this week to review it and merge it. I'll let you know if I see some change to make.

Victor

**Comment by pvictor** [comment]
Hello @xiangnandang,

I finally had time to review that PR, i've made some changes for x/y limits, and added you as contributor in DESCRIPTION with:

```r
person("Xiangnan", "Dang", comment = "Facets rows and cols, X/Y limits", role = "ctb")
```

Is that good for you before I merge ?

Victor

**Comment by xiangnandang** [comment]
Hi @pvictor,

Thank you! I'm good with the changes.

Xiangnan

**Comment by pvictor** [comment]
Perfect! Merged 🎉

**Comment by picousse** [comment]
Hi,
Does this mean facetting in both directions should be possible?
Best regards,
pieter

**Comment by xiangnandang** [comment]
@picousse, yes facet_grid has been implemented, along with adjusting nrow for facet_wrap.

Cheers,
Xiangnan

**Comment by picousse** [comment]
cool stuff! exactly what I needed.

Thanks

**Comment by xiangnandang** [comment]
@picousse , sorry that i just realized in this original merge, I forgot to change the dragulaInput to surface the facet_row and facet_col, even though the other codes were already there. I just submitted #113 to fix this.

**Pull request merged**
