### PR TITLE
Restore state with bookmarking

### PR DESCRIPTION
**Pull request by itcarroll**
Shiny 0.14 introduced [bookmarking](https://shiny.rstudio.com/articles/bookmarking-state.html), an easy was to save the state of inputs for restoring an app to the saved state. The esquisse modules had to be modified in a few ways for bookmarking to succeed, most critically

1. The `dragulaInput` needed to use `shiny::restoreInput` to check for saved states.
2. The entire module needed to be stateful (the outputs must be fully determined by inputs at any given time, with no server code run in between).

Step 1 was easy, step 2 took some refactoring. For example the function `updateDragulaInput` had to be made obsolete, replacing instead with a reactive `renderUI` that took data as a dependency. The removeUI/insertUI pairing for the filterData module, including its randomly generated namespace key, had be be replaced with a renderUI.

I took the liberty of including axis transformations in this PR as well, as interest had recently been expressed (#24).

I will attempt to address any issues arising in your testing. Thanks for considering!

### CODE REVIEW

**Comment by pvictor** [comment]
Hi Ian,
Thanks for the PR and sorry for the late answer. 
Can you put back `updateDraguaInput` ? Since it's an exported function from the package, people can use it outside of the addin.
After that, I think it's good to merge !

Victor

**Comment by itcarroll** [comment]
Thanks, I will add it back! May I include the caveat in the module's documentation that a dragulaInput modified by updateDragulaInput will not be restorable with shiny bookmarking?

**Comment by pvictor** [comment]
Sure! Thx!

**Comment by pvictor** [comment]
Hi @itcarroll ,
Mmmh I'm sorry I broke everything meantime to use `rlang` for generating the code and the plot.
I cannot merge this as is, but I have  included axis transformations however.
Bookmarking is still to do, but I'll take a look at it from what you've already done.

Victor

**Pull request closed without merging**
